baseURL = "https://ompugao.github.io/resume/"
languageCode = "en-us"
title = "Shohei Fujii's Portfolio"

# [menu]
#   [[menu.main]]
#     name = "Home"
#     url = "/"
#     weight = 1
#   [[menu.main]]
#     name = "Education"
#     url = "/education/"
#     weight = 2
#   [[menu.main]]
#     name = "Projects"
#     url = "/projects/"
#     weight = 3
#   [[menu.main]]
#     name = "Experience"
#     url = "/experience/"
#     weight = 4
#   [[menu.main]]
#     name = "Publications"
#     url = "/publications/"
#     weight = 5
#   [[menu.main]]
#     name = "Awards"
#     url = "/awards/"
#     weight = 6

[params]
    author = "Shohei Fujii"
    description = "Passionate about Robotics and Automation, dedicated to eliminating tedious tasks from this world."
    [params.profile]
        name = "Shohei Fujii"
        title = "Ph.D. in Robotics"
        photo = "images/profile.jpg"
    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
        icon = "fab fa-linkedin-in"
        url = "https://www.linkedin.com/in/shohei-fujii"
        title = "LinkedIn"

        [[params.social.list]]
        icon = "fab fa-github"
        url = "https://github.com/ompugao"
        title = "GitHub"

[services]
    [services.googleAnalytics]
        id = 'G-F46WDJKTFN'

[markup.goldmark.renderer]
  unsafe = true
